<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Legal Notices</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  

  </head>
  <body style="padding-top: 95px">

    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-between">
          <a class="navbar-brand" href="#">Legal Notices</a>
        </nav>
      </div>
    </div>
    
    <!-- content area -->
    <div class="container">
      <ul>
        <li>This application is intended for demonstration purposes only and is provided without any warranties or safeguards. Users are hereby warned that they should not store any sensitive or confidential information within it. The application author takes no responsibility or liability for any data loss arising from usage of this application.</li>
        <li>By using this application, you agree to be bound by the ClearDB Terms of Service, available at <a href="http://w2.cleardb.net/terms/">http://w2.cleardb.net/terms/</a> and to comply with (and not knowingly violate) applicable law, regulation, and these terms of use.</li>
        <li>By using this application, you agree to be bound by the IBM Cloud Terms of Use, available at <a href="http://www-03.ibm.com/software/sla/sladb.nsf/sla/saas">http://www-03.ibm.com/software/sla/sladb.nsf/sla/saas</a> and to comply with (and not knowingly violate) applicable law, regulation, and these terms of use.</li>
        <li>By using this application, you agree to defend, indemnify and hold harmless the application author, from and against all costs, charges and expenses (including attorneys' fees) arising from any third party claim, action, suit, or proceeding against any action by a third party against the application author.</li>
      </ul>    
    </div>        
    <!-- content area ends-->
      
    <!-- footer -->
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
      </p>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>