<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>List Time Entries</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  

  </head>
  <body style="padding-top: 95px">

    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-between">
          <a class="navbar-brand" href="#">Time entries</a>
          <span>
            <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('projects-list'); ?>">List projects</a>
            <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('entries-save'); ?>">Add time entry</a>
          </span>
        </nav>
      </div>
    </div>
    
    <!-- content area -->
    <div class="container">
      
      <h2>
        Project: <?php echo htmlspecialchars($data['project']->name, ENT_COMPAT, 'UTF-8'); ?>
        <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('entries-list', array('id' => htmlspecialchars($data['project']->id, ENT_COMPAT, 'UTF-8'), 'download' => true)); ?>">Download data</a>
      </h2>
      <?php $count = 1; ?>
      <?php $total = 0; ?>
      <?php if (count($data['entries'])): ?>
      <table class="table table-border table-responsive-md">
        <thead>
          <tr>
            <th>#</th>
            <th>Date</th>
            <th>Hours</th>
            <th>Comment</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($data['entries'] as $entry): ?>
        <tr>
          <td><?php echo $count; ?></td>
          <td><?php echo htmlspecialchars($entry['date'], ENT_COMPAT, 'UTF-8'); ?></td>
          <td><?php echo htmlspecialchars($entry['hours'], ENT_COMPAT, 'UTF-8'); ?></td>
          <td><?php echo htmlspecialchars($entry['comment'], ENT_COMPAT, 'UTF-8'); ?></td>
          <td><a role="button" class="btn btn-danger" href="<?php echo $data['router']->pathFor('entries-delete', array('id' => htmlspecialchars($entry['id'], ENT_COMPAT, 'UTF-8'))); ?>">Delete entry</a></td>
        </tr>
        <?php $total += $entry['hours']; ?>
        <?php $count++; ?>
        <?php endforeach; ?>
        <tr>
          <td></td>
          <td><strong>TOTAL</strong></td>
          <td><strong><?php echo $total; ?></strong></td>
          <td colspan="2"></td>
        </tr>
        </tbody>
      </table>
      <?php endif; ?>
    </div>        
    <!-- content area ends-->
      
    <!-- footer -->
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
      </p>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>