<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Time Entry</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  

  </head>
  <body style="padding-top: 95px">

    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-between">
          <a class="navbar-brand" href="#">Time entry</a>
          <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('projects-list'); ?>">List projects</a>
        </nav>
      </div>
    </div>
    
    <!-- content area -->
    <div class="container">
    <?php if (!isset($_POST['submit'])): ?>
      <form method="post" action="<?php echo $data['router']->pathFor('entries-save'); ?>">
        <div class="form-group">
          <label for="pid">Project</label>
          <select class="form-control" id="pid" name="pid">
          <?php foreach ($data['projects'] as $project): ?>
            <option value="<?php echo htmlspecialchars($project['id'], ENT_COMPAT, 'UTF-8'); ?>"><?php echo htmlspecialchars($project['name'], ENT_COMPAT, 'UTF-8'); ?></option>
          <?php endforeach; ?>
          </select>
        </div>
        <div class="form-group">
          <label for="date">Date</label>
          <input type="date" class="form-control" id="date" name="date">
        </div>
        <div class="form-group">
          <label for="hours">Hours spent</label>
          <input type="text" class="form-control" id="hours" name="hours">
        </div>
        <div class="form-group">
          <label for="comment">Comment</label>
          <input type="text" class="form-control" id="comment" name="comment">
        </div>
        <div class="form-group">
          <button type="submit" name="submit" class="btn btn-success">Save</button>
        </div>
      </form>  
    <?php else: ?>
      <div class="alert alert-success" role="alert">
        <strong>Success!</strong> The time entry was successfully created or updated.
      </div>
    <?php endif; ?> 
    </div>        
    <!-- content area ends-->
      
    <!-- footer -->
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
      </p>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>