<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>List Projects</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  

  </head>
  <body style="padding-top: 95px">

    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-between">
          <a class="navbar-brand" href="#">Projects</a>
          <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('projects-save'); ?>">Add project</a>
        </nav>
      </div>
    </div>
    
    <!-- content area -->
    <div class="container">
      <?php if (count($data['projects'])): ?>
      <table class="table table-border table-responsive-md">
        <thead>
          <tr>
            <th>#</th>
            <th>Project</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <?php foreach ($data['projects'] as $project): ?>
        <tr>
          <td><?php echo htmlspecialchars($project['id'], ENT_COMPAT, 'UTF-8'); ?></td>
          <td><?php echo htmlspecialchars($project['name'], ENT_COMPAT, 'UTF-8'); ?></td>
          <td><a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('entries-save'); ?>">Add entry</a></td>
          <td><a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('entries-list', array('id' => htmlspecialchars($project['id'], ENT_COMPAT, 'UTF-8'))); ?>">View entries</a></td>
          <td><a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('projects-save', array('id' => htmlspecialchars($project['id'], ENT_COMPAT, 'UTF-8'))); ?>">Modify project</a></td>
          <td><a role="button" class="btn btn-danger" href="<?php echo $data['router']->pathFor('projects-delete', array('id' => htmlspecialchars($project['id'], ENT_COMPAT, 'UTF-8'))); ?>">Delete project</a></td>
        </tr>
        <?php endforeach; ?>
      </table>
      <?php endif; ?>
    </div>        
    <!-- content area ends-->
      
    <!-- footer -->
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
      </p>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>